# Generated by Django 4.1.3 on 2023-01-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0002_alter_meal_meal_type'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclick',
            name='category',
        ),
        migrations.AddField(
            model_name='userclick',
            name='category',
            field=models.ManyToManyField(related_name='Категория', to='cafe_core_app.meal'),
        ),
    ]
