# Generated by Django 4.1.3 on 2023-01-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userclick_category_userclick_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclick',
            name='category',
        ),
        migrations.AddField(
            model_name='userclick',
            name='category',
            field=models.CharField(default=1, max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
