# Generated by Django 4.1.3 on 2023-01-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userclick_category_userclick_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserClick',
        ),
    ]
