# Generated by Django 4.1.3 on 2023-01-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('price', models.IntegerField(verbose_name='Цена блюда')),
                ('size', models.IntegerField(verbose_name='Граммовка блюда')),
                ('meal_type', models.CharField(choices=[('Горячие блюда', 'Hot Meals'), ('Напитки', 'Drink'), ('Десерты', 'Desserts'), ('Без типа', 'No Type')], default='Без типа', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MealClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата клика')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe_core_app.meal')),
            ],
        ),
    ]
