# Generated by Django 4.1.3 on 2023-01-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0003_userclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('Горячие блюда', 'Hot Meals'), ('Напитки', 'Drink'), ('Десерты', 'Desserts'), ('NO_TYPE', 'No Type')], default='NO_TYPE', max_length=20, verbose_name='Категория блюда'),
        ),
    ]
