# Generated by Django 4.1.3 on 2023-01-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0004_alter_meal_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, height_field=500, null=True, upload_to='images/', width_field=500),
        ),
    ]
