# Generated by Django 4.1.3 on 2023-01-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0005_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
