# Generated by Django 4.1.3 on 2023-01-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0006_alter_meal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='image',
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafe_core_app.meal')),
            ],
        ),
    ]
